### ISSUE TITLE
support for non-windows platforms

### ISSUE THREAD

**Issue by jseifertscionics** [gregory-kyro/CardioGenAI#1]
Hi,
i just tired to install the env on a linux machine and after some fiddling and wondering i noticed that the dependencies are windows specific (some of the packages are only available on windows).
Could you share steps to use this software on other platforms? If no other platform is supported it would also help to write this in the beginning of the installation steps to avoid having people spend hours fruitlessly debugging that process.

Thank you!

**Comment by gregory-kyro** [comment]
Thank you for the suggestion. I apologize for the trouble that you went through trying to get the software to work on a Linux machine. We are working on improving compatibility across different devices, and I will reach out as soon as we have ensured compatibility with Linux.
